### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hoochie63** [James-Fire/James-Train-Mod_1.0.0#5]
Hi!
I built a gas station on regular rails, and to check the traffic lights, I put an electric train on the rails. and an error popped up.

Error while running event James-Train-Mod::on_tick (ID 0)
Unknown item name: electric-burner-item
stack traceback:
	[C]: in function '__newindex'
	__James-Train-Mod__/scripts/powered-rails.lua:230: in function 'PowerTrain'
	__James-Train-Mod__/scripts/powered-rails.lua:357: in function 'UpdateTrains'
	__James-Train-Mod__/scripts/powered-rails.lua:373: in function <__James-Train-Mod__/scripts/powered-rails.lua:370>

![image](https://github.com/user-attachments/assets/6cb96d7e-6bef-4d93-9a37-75811035ca5b)

**Comment by James-Fire** [comment]
Can you send your save?

**Comment by Hoochie63** [comment]
[_autosave1.zip](https://github.com/user-attachments/files/18206239/_autosave1.zip)

**Comment by James-Fire** [comment]
Alright well I ran into 2 separate issues trying to load your save to see what was going on.

First was that KS Power apparently defines an entity twice, so I had to disable it and the rebalance.

Second was that as soon as I loaded into the save, Toolbars caused a runtime error, so I can't even look around in the save.

However, I can say that the error is caused by some other mod, for some reason, deleting my hidden fuel item. Which is obviously bad for a mod to do. I don't know if I'd be able to figure out which one is doing it even if your save did work.

So as far as I'm concerned, this isn't my problem, and I can't do anything about it anyway.
